### ISSUE TITLE
Cannot run PyNAPLE correctly on WSL2 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by zhouxuanxiao** [dsheward-astro/PyNAPLE#1]
Dear Dr. Dianel Sheward.

First of all, thank you very much for sharing your code. I am more interested in this, so I tried to configure and run PyNAPLE on the WSL2-Ubuntu20.04 system (with X server in MobaXterm). I followed the tutorial you gave and performed the following steps:

conda create -n PyNAPLE python=3.6
conda activate PyNAPLE
pip installl mechanize && bs4 && matplotlib && tkcalendar && shapely
conda deactiavte PyNAPLE
conda activate isis
conda activate --stack PyNAPLE
sudo chmod a+x PyNAPLE.py
mkdir img
mkdir processed
./PyNAPLE.py

The GUI of the PyNAPLE program can be opened normally, but the following error will appear when the 'Calibrating image' is executed. I don't know how to solve it yet. I hope to get your help:

--------------------------------------------------------
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/wsl2/anaconda3/envs/PyNAPLE/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "./PyNAPLE.py", line 1010, in checkRunPynaple
    self.runPyNAPLE()
  File "./PyNAPLE.py", line 1019, in runPyNAPLE
    self.pynapleInstance = PyNAPLE(self)
  File "./PyNAPLE.py", line 146, in __init__
    self.pynaple()
  File "./PyNAPLE.py", line 163, in pynaple
    success = self.process(*pair)
  File "./PyNAPLE.py", line 226, in process
    preimg.downloadImage()
  File "./PyNAPLE.py", line 687, in downloadImage
    sp.check_call([". ./../runIsis.sh && "+operation], shell=True, executable="/bin/bash", cwd=self.directory+"/img", stdout=DEVNULL, stderr=DEVNULL)
  File "/home/wsl2/anaconda3/envs/PyNAPLE/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['. ./../runIsis.sh && lronac2isis from=M1116714278LE.IMG to=M1116714278LE.cub']' returned non-zero exit status 1.
--------------------------------------------------------

It should be noted that I have successfully installed and registered ISIS6.0, and the ISISROOT= /home/wsl2/anaconda3/envs/isis. According to the content of the error, I have created '**runIsis.sh**' in /home/wsl2/anaconda3/envs/PyNAPLE/lib/python3.6/, and the content is as follows (but it doesn't work and still exist):

#!/usr/bin/env sh
         ISISROOT=/home/wsl2/anaconda3/envs/isis
         export ISISROOT
         . $ISISROOT/scripts/isis3Startup.sh

Thanks and Very Best Regards,

Zhouxuan Xiao, PhD student from Sun Yat-sen Univeristy
Email: xiaozhx7@mail2.sysu.edu.cn

**Comment by dsheward-astro** [comment]
Hi, 
I have examined the issue and found that there is currently an incompatibility between PyNAPLE and ISIS3 versions 6+, I am currently working to update PyNAPLE to ISIS3 6.0, but in the mean time ISIS3 3.5 is required - a link to the installation guide for 3.5 is in the README.

Thanks, 
Daniel

**Comment by zhouxuanxiao** [comment]
Many thanks for your  kind reply, I'll try to run PyNAPLE with ISIS 3.5. Hope everything works well in the next.

Yours sincerely,
Zhouxuan Xiao

**Comment by zhouxuanxiao** [comment]
Dear Dr. Dianel Sheward:

I feel sorry to bother you again. I have already try your advice, but there still be the similar errors as follws:

_____________________________________________________
Now Running...
/home/wsl2/anaconda3/envs/isis3/lib/python3.6/site-packages/shapely/geometry/polygon.py:261: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  ret = geos_polygon_from_py(shell, holes)
/home/wsl2/anaconda3/envs/isis3/lib/python3.6/site-packages/shapely/geometry/polygon.py:539: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  ret = geos_linearring_from_py(shell)

Searching for Images...
3 before and 4 after images found
5 temporal pairs found
Temporal pair: M1151638664RE & M1325732852LE
Downloading image M1151638664RE
Calibrating image M1151638664RE
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/wsl2/anaconda3/envs/isis3/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "./PyNAPLE.py", line 1010, in checkRunPynaple
    self.runPyNAPLE()
  File "./PyNAPLE.py", line 1019, in runPyNAPLE
    self.pynapleInstance = PyNAPLE(self)
  File "./PyNAPLE.py", line 146, in __init__
    self.pynaple()
  File "./PyNAPLE.py", line 163, in pynaple
    success = self.process(*pair)
  File "./PyNAPLE.py", line 226, in process
    preimg.downloadImage()
  File "./PyNAPLE.py", line 687, in downloadImage
    sp.check_call([". ./../runIsis.sh && "+operation], shell=True, executable="/bin/bash", cwd=self.directory+"/img", stdout=DEVNULL, stderr=DEVNULL)
  File "/home/wsl2/anaconda3/envs/isis3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['. ./../runIsis.sh && lronac2isis from=M1151638664RE.IMG to=M1151638664RE.cub']' returned non-zero exit status 4.
_____________________________________________________


My 'runIsis.sh' (/home/wsl2/PyNAPLE/runIsis.sh):
#!/bin/bash
ISISROOT=/mnt/d/isis3/isis
. $ISISROOT/scripts/isis3Startup.sh isis3

My OS system:
WSL2-Ubuntu 20.04 LTS

My ISIS3 version:
3.5.2 (/mnt/d/isis3/isis)

My PyNAPLE location:
/home/wsl2/PyNAPLE (./img & ./processed & ./PyNAPLE.py & CONFIG etc.)

My X server software:
MobaXterm Home Edition (with X11)

___

So,I'm wondering if I need to downgrade Ubuntu to lower version or if I should change the directory where  'runIsis.sh 'is placed.

Very Best Regards,
Zhouxuan Xiao

**Comment by zhouxuanxiao** [comment]
Dear Dr. Dianel Sheward:

Sorry about the last comment, I have correctly run PyNAPLE now. Thanks

Kind Regards,
Zhouxuan Xiao
